exports.COURSE_PENDING = 0;
exports.COURSE_APPROVED = 1;
exports.COURSE_STATUS = [this.COURSE_PENDING, this.COURSE_APPROVED];

exports.STUDENT = 0;
exports.INSTRUCTOR = 1;
exports.ADMIN = 2;
exports.OWNER = 3;
exports.USER_TYPES = [this.STUDENT, this.INSTRUCTOR, this.ADMIN, this.OWNER];

exports.QUESTION_COMPLETE = 0;
exports.QUESTION_CHOICE_ONE = 1;
exports.QUESTION_TRUE_OR_FALSE = 2;
exports.QUESTION_ESSAY = 3;
exports.QUESTION_SPEECH = 4;

exports.QUESTION_TYPES = [
	this.QUESTION_COMPLETE,
	this.QUESTION_CHOICE_ONE,
	this.QUESTION_TRUE_OR_FALSE,
	this.QUESTION_ESSAY,
];
