exports.COURSE_PENDING = 0;
exports.COURSE_APPROVED = 1;
exports.COURSE_STATUS = [this.COURSE_PENDING, this.COURSE_APPROVED];

exports.USER_STUDENT = 0;
exports.USER_INSTRUCTOR = 1;
exports.USER_ADMIN = 2;
exports.USER_OWNER = 3;
exports.USER_TYPES = [this.USER_STUDENT, this.USER_INSTRUCTOR, this.USER_ADMIN, this.USER_OWNER];

exports.QUESTION_COMPLETE = 0;
exports.QUESTION_CHOICE_ONE = 1;
exports.QUESTION_TRUE_OR_FALSE = 2;
exports.QUESTION_ESSAY = 3;
exports.QUESTION_SPEECH = 4;

exports.QUESTION_TYPES = [
	this.QUESTION_COMPLETE,
	this.QUESTION_CHOICE_ONE,
	this.QUESTION_TRUE_OR_FALSE,
	this.QUESTION_ESSAY,
];
